name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3.9 -m pip install --upgrade pip
        pip3.9 install -r requirements.txt
    - name: Save pip dependencies as artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: pip-packages
        path: ~/.cache/pip

  run_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download pip dependencies artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: pip-packages
        path: ~/.cache/pip
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip3.9 install -r requirements.txt
    - name: Run Tests
      run: |
        cd backend
        python3.9 manage.py test

  deploy:
    needs: run_tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Production server
      uses: easingthemes/ssh-deploy@v4.1.10
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "backend/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.BACKEND_REMOTE_TARGET }}
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
          cd ${{ secrets.BACKEND_REMOTE_TARGET }}
          python3.9 manage.py makemigrations
          python3.9 manage.py migrate
          sudo systemctl restart uwsgi.service
